Repository trustbloc/docs, pull requests merged in 2020-08, with the labels that each got.

#20 docs: added more templates and made general updates
  README.md
  docs/source/conf.py
  docs/source/configuration_deployment.rst
  docs/source/index.rst
  docs/source/introduction.rst
  docs/source/projects.rst
  docs/source/questions.rst
Labels: cla-signed, documentation, enhancement

#22 docs: rearranged pages, topics and content
  docs/source/adapters.rst
  docs/source/configuration_deployment.rst
  docs/source/index.rst
  docs/source/vcs.rst
  docs/source/wallet_chapi.rst
Labels: cla-signed, documentation, enhancement

#30 docs: added flows, demos and diagrams for VCS and Adapter docs
  docs/source/_templates/footer.html
  docs/source/adapters.rst
  docs/source/images/didcomm_component_diagram.svg
  docs/source/images/nondidcomm_component_diagram.svg
  docs/source/introduction.rst
  docs/source/vcs.rst
Labels: cla-signed, documentation, enhancement

#31 fix: change the image reference structure
  docs/source/adapters.rst
Labels: bug, cla-signed

#32 docs: update RP adapter integration link
  docs/source/adapters.rst
  docs/source/features.rst
  docs/source/index.rst
Labels: chore, cla-signed, documentation

#33 docs: for configuring edge service
  docs/source/vcs.rst
Labels: cla-signed, documentation

#34 docs: Update Adapter and VCS demo component diagram
  docs/source/adapters.rst
  docs/source/images/adapter_component_diagram.svg
  docs/source/images/didcomm_component_diagram.svg
  docs/source/images/nondidcomm_component_diagram.svg
  docs/source/images/vcs_component_diagram.svg
Labels: cla-signed

#35 docs: Fix adapter/vcs related docs
  docs/source/adapters.rst
  docs/source/vcs.rst
Labels: cla-signed

#36 docs: adapter configuration, VCS deployments images, other updates
  docs/source/adapters.rst
  docs/source/images/sandbox-deployment/docker-compose-didcomm.yml.png
  docs/source/images/sandbox-deployment/docker-compose-edge-components.yml.png
  docs/source/images/sandbox-deployment/docker-compose-sidetree-fabric.yml.png
  docs/source/images/sandbox-deployment/docker-compose-sidetree-mock.yml.png
  docs/source/images/sandbox-deployment/docker-compose-universal-registrar.yml.png
  docs/source/images/sandbox-deployment/docker-compose-universal-resolver.yml.png
  docs/source/introduction.rst
  docs/source/vcs.rst
Labels: cla-signed, documentation
